### PR TITLE
Fix DAGLayer moving out of gpu during optimization step

### PR DESCRIPTION
**Pull request by samialabed**
## Motivation and Context

Quick bug fix:
During the optimizer step the DAG parameters are being replaced with tensors that live on the CPU rather than on the GPU.
This change basically make sure these tensors are being sent to the same device the model was originally on. 

Without this fix, you will get error: "Expected all tensors to be on the same device..." 

Longer term solution: I would refactor the device assignment - rather than relying on default dtype or calling to(device), create a single call at model creation that sets the dtype and device and use that for all layers and parameters.  
I used Black Linter. Will add test and ensure to use the same linter as the project after my paper deadline, this quick fix to help anyone else who was stuck on this :) 

## How has this been tested?
Ran few examples on my data.

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](/RELEASE.md) file
- [ ] Added tests to cover my changes
- [x] Assigned myself to the PR

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by oentaryorj** [comment]
Thanks for your contribution @samialabed. Do let us know once you finalise the code and test cases.

**Comment by oentaryorj** [comment]
Hi @samialabed, hope you are well. May we know if there is an update on the test cases? Unfortunately, at this point we don't have a GPU machine to test the changes, so we appreciate if you can help on your side. Thanks! :)

**Comment by galfaroi** [comment]
Hi, how can I do the bug fix, before the PR is done?

**Comment by BruceXu1991** [comment]
> Hi @samialabed, hope you are well. May we know if there is an update on the test cases? Unfortunately, at this point we don't have a GPU machine to test the changes, so we appreciate if you can help on your side. Thanks! :)

I have tested this PR on GPU and it works well on develop branch.

**Comment by samialabed** [comment]
Hi Bruce, apologizes I got very busy with various work streams and I forgot to get back on this.

I haven't found a clean way to test the device placement as a unit test, if you know a way let me know and I am happy to add the tests.

I did however, test this change on multiple devices for my experiments and it works as intended.

**Review by oentaryorj — APPROVED** [review]

**Review by GabrielAzevedoFerreiraQB — APPROVED** [review]
LGTM

**Comment by oentaryorj** [comment]
A more formal, cleaner way for GPU testing would be needed, but due to urgency we shall merge this PR first. Feel free to open another PR for the formal testing

**Comment by oentaryorj** [comment]
This should address [this issue](https://github.com/quantumblacklabs/causalnex/issues/138) as well

**Pull request merged**
