### PR TITLE
01_prerequisites.md: Indicate PyTorch requirement

### PR DESCRIPTION
**Pull request by jeffchiou**
Minor edit - latest version seems to require PyTorch, so I added the requirement to prerequisites. 

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

## Motivation and Context
Keep docs up-to-date

## How has this been tested?
Tried running causalnex without pytorch; didn't work.

## Checklist

- [x] Read the [contributing](/CONTRIBUTING.md) guidelines
- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [ ] Added a description of this change and added my name to the list of supporting contributions in the [`RELEASE.md`](/RELEASE.md) file
- [ ] Added tests to cover my changes
- [ ] Assigned myself to the PR

### CODE REVIEW

**Comment by qbphilip** [comment]
Hello Jeff, thanks for your PR.

You are right that it currently is necessary to have pytorch because of how we import the modules (see #69).

From a requirements perspective, we already have pytorch as optional as it is quite chunky.
However, this doesn't show in the requirements and only in the `setup.py`:
```
extras_require = {
    "plot": [
        "pygraphviz>=1.5, <2.0",
    ],
    "pytorch": ["torch>=1.4.0, <2.0"],
}
```

I will leave the PR open for now. If we are able to merge (quickly) the PR that separates the modules with optional dependencies I will close this PR.

**Comment by qbphilip** [comment]
Turns out that the latest pgmpy requires torch!

**Review by qbphilip — APPROVED** [review]
Thanks Jeff!

Seems like we need to promote torch to full requirement.
In that spirit, this PR is a valuable contribution!

**Review by mzjp2 — APPROVED** [review]
Thank you!

**Pull request merged**
