### PR TITLE
Fix: pygraphviz gradient string can not be rendered correctly on Windows

### PR DESCRIPTION
**Pull request by JarodYv**
When I tried to visualize a model on Windows using `plot_structure` , I got black colored edges with shifted position, as the image below:

output

Well, I think this is a compatibility issue from graphviz on Windows. If I shorten the gradient string, it can be rendered perfectly. So I cut down the `steps`, make sure it‘s never greater than 7. 

This is the out plotting after fixing:
 
output2

### CODE REVIEW

**Comment by oentaryorj** [comment]
Thanks for your contribution, @JarodYv. Overall the PR looks good to me, but please help fix the linting issue (e.g., you can run `make lint` before submitting your commit) as well as the unit test for `causalnex/plots/plots.py`.

**Comment by JarodYv** [comment]
I've run `make lint` and added unit test to my code. All test passed and coverage of 100% reached.

**Review by GabrielAzevedoFerreiraQB — COMMENTED** [review]
Hi @JarodYv, 

First or all, thanks so much for the awesome contribution!

This makes a lot of sense to me, but I just wanted to investigate 3 things before we merge it:

- I wonder why this happens on windows/if it is an issue that Graphviz is aware and working on
- can the gradient "resolution" be "visible" in certain cases (we can try plotting a large edge with high weight - which will make it "thicker". Then we'll see if the points were the gradient changes are clear)
- If 7 is the magic number or we can push a bit more? (if the previous question is good we don't need to worry about it too much though)

**Comment by JarodYv** [comment]
Well, finally, I figured out that the problem was caused by graphviz. Now graphviz has fixed the bug on windows and if I update graphviz to the latest version, the problem above disappears. I think this PR should be closed. Sorry for taking up your time.

**Pull request closed without merging**
