### PR TITLE
fix: cpd floating point comparison issue

### LINKED ISSUE #171: Floating Point Comparison Issues
## Description
`ie.do_intervention` [requires](https://github.com/quantumblacklabs/causalnex/blob/426260913861796094a624a3807b8736713989e0/causalnex/inference/inference.py#L208) the CPD to sum up exactly to 1.0.  But this requirement is sometimes not achievable due to python floating point arithmetic limitations. Hence some of the distributions may sum up to 1.0 ± _eps_, where _eps_ is close to 0.

## Context
Found this cpd from the real world data: `[0.348, 0.328, 0.182, 0.142]`.
Looks like it sums to 1. But here comes the floating point arithmetic.
```python
>>>sum([0.348, 0.328, 0.182, 0.142])
0.9999999999999999
```

## Steps to Reproduce
```python
ie.do_intervention("node", {"a": 0.348 , "b": 0.328, "c": 0.182, "d":0.142})
```

## Actual Result
```python
ValueError("The cpd for the provided observation must sum to 1")
```

## Expected Result
No error

## Your Environment
causalnex==0.11.0

### PR DESCRIPTION
**Pull request by ivandkh**
## Motivation and Context
fixes #171

## How has this been tested?
What testing strategies have you used?

## Notice

- [x] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

### CODE REVIEW

**Comment by oentaryorj** [comment]
Thanks for this PR. Can you help address the linting issue please? Looks like it is due to ordering issue of `import math`. You may run `make lint` before you commit.

**Review by oentaryorj — APPROVED** [review]
LGTM

**Review by EvgeniiaVeselova — APPROVED** [review]
LGTM

**Review by GabrielAzevedoFerreiraQB — APPROVED** [review]
Thanks for fixing it, Ivan!

Makes sense to me, we can merge it :)

**Pull request merged**
